config/routes.rb
Rails.application.routes.draw do
  get 'processos/index'
  get 'processos/show'
  get 'processos/new'
  get 'processos/create'
  get 'processos/edit'
  get 'processos/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :processos, except: %i[destroy]
  resources :itens, except: %i[destroy new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :processo, optional: true
end

app/models/pac.rb
class Pac < ApplicationRecord
  has_many :itens
end

app/models/processo.rb
class Processo < ApplicationRecord
  has_many :itens
  DEMANDANTE = ["CGLOG/DIRAD", "CGPEO/DIRAD", "CGCOM/DIRAD", "CGGOV/DIRTI", "CGINF/DIRTI", "CGDES/DIRTI", "CGPLI/DIRAE", "CGPAE/DIRAE", "CGIMP/DIGAP", "CGEOF/DIFIN", "CGFIN/DIGEF", "ASSEC/PRESI", "OUVID/PRESI", "AGEST/PRESI", "GABIN/PRESI"]
  TIPO = ["Pregão", "Dispensa de licitação", "Inexigibilidade", "Adesão ARP"]
  FASE = ["Tramitação inicial", "ETP/Mapa de riscos", "TR/PB", "Instrução pré-PROFE", "PROFE", "Instrução pós-PROFE", "Fase externa - SIASG / Comprasnet", "Autoridade competente / empenho", "Contrato em execução", "Processo encerrado"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  before_action :set_processo, only: %i[show edit update]

  def index
    @processos = Processo.all
  end

  def show
  end

  def new
    @processo = Processo.new
  end

  def create
    @processo = Processo.new(processo_params)
    if @processo.save
      # redirect_to processos_path
      redirect_to processo_path(@processo), notice: 'O processo foi criado.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @processo.update(processo_params)
    redirect_to processo_path(@processo), notice: 'O processo foi atualizado.'
  end

  private

  def set_processo
    @processo = Processo.find(params[:id])
  end

  def processo_params
    params.require(:processo).permit(:sei, :objeto, :demandante, :tipo_contratacao, :fase, :data_inicio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compras Internas FNDE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/processos/_form.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <%= simple_form_for @processo do |f| %>
        <%= f.error_notification %>
        <%= f.input :sei, label:"Número SEI" %>
        <%= f.input :objeto, as: :text, label:"Objeto da contratação" %>
        <%= f.input :demandante, label:"Área demandante", collection: Processo::DEMANDANTE, prompt: "Selecione" %>
        <%= f.input :tipo_contratacao, label:"Tipo de contratação", collection: Processo::TIPO, prompt: "Selecione" %>
        <%= f.input :data_inicio, as: :date, html5: true, label:"Data de início do processo" %>
        <%= f.input :fase, label:"Fase do processo", collection: Processo::FASE, prompt: "Selecione" %>
        <%= f.button :submit, "Salvar", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/processos/edit.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Editar processo:</h1>
      </div>
  </div>
</div>
<%= render "form", processo: @processo %>

app/views/processos/index.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="d-flex justify-content-between">
        <h1>Processos</h1>
        <div>
          <%= link_to 'Novo processo <i class="fas fa-plus-square"></i>'.html_safe, new_processo_path, class: "btn btn-primary" %>
        </div>
      </div>
      <br>
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="align-middle" scope="col">Processo</th>
            <th class="align-middle" scope="col">Objeto</th>
            <th class="align-middle" scope="col">Demandante</th>
            <th class="align-middle" scope="col">Tipo de contratação</th>
            <th class="align-middle" scope="col">Data de início do processo</th>
            <th class="align-middle" scope="col">Fase atual</th>
            <th class="align-middle" scope="col">Última atualização</th>
            <th class="align-middle" scope="col">Tempo em tramitação</th>
            <th class="align-middle" scope="col">Detalhar</th>
          </tr>
        </thead>
        <tbody>
          <% @processos.each do |processo| %>
            <tr>
            <td><%= processo.sei %></td>
            <td><%= processo.objeto %></td>
            <td><%= processo.demandante %></td>
            <td><%= processo.tipo_contratacao %></td>
            <td><%= processo.data_inicio.strftime("%d/%m/%Y") %></td>
            <td><%= processo.fase %></td>
            <td><%= processo.updated_at.strftime("%d/%m/%Y") %></td>
            <td><%= time_ago_in_words(processo.data_inicio) %></td>
            <td><%= link_to '<i class="fas fa-search"></i>'.html_safe, processo_path(processo), class: "btn btn-primary"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/processos/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Cadastrar novo processo:</h1>
      </div>
  </div>
</div>
<%= render "form", processo: @processo %>

app/views/processos/show.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="d-flex justify-content-between">
        <h2>Processo <%= @processo.sei %></h2>
        <div>
          <%= link_to 'Editar processo <i class="fas fa-edit"></i>'.html_safe, edit_processo_path(@processo), class: "btn btn-primary"%>
        </div>
      </div>
      <br>
      <div>
        <p><strong>Objeto:</strong> <%= @processo.objeto %></p>
      </div>
      
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Demandante</th>
            <th scope="col">Tipo de contratação</th>
            <th scope="col">Data de início do processo</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @processo.demandante %></td>
            <td><%= @processo.tipo_contratacao %></td>
            <td><%= @processo.data_inicio.strftime("%d/%m/%Y") %></td>
          </tr>
        </tbody>
      </table>

      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Fase atual</th>
            <th scope="col">Última atualização</th>
            <th scope="col">Tempo em tramitação</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @processo.fase %></td>
            <td><%= @processo.updated_at.strftime("%d/%m/%Y") %></td>
            <td><%= time_ago_in_words(@processo.data_inicio) %></td>
          </tr>
        </tbody>
      </table>
      
      <div class="d-flex justify-content-around">
        <%= link_to 'Listar processos <i class="fas fa-list"></i>'.html_safe, processos_path, class: "btn btn-primary" %>
        <%= link_to 'Novo processo <i class="fas fa-plus-square"></i>'.html_safe, new_processo_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>